"""Stock ubicacion con producto_id

Revision ID: 4e157985dff8
Revises: e8391851b7fd
Create Date: 2025-05-16 21:53:33.571519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e157985dff8'
down_revision = 'e8391851b7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_stock_ubicacion')
    with op.batch_alter_table('stock_ubicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint('uq_area_codigo', type_='unique')
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])
        batch_op.drop_column('producto_nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_ubicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_nombre', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('uq_area_codigo', ['area_id', 'codigo'])
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('producto_id')

    op.create_table('_alembic_tmp_stock_ubicacion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='fk_stock_producto'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
