"""Inicialización de la base de datos

Revision ID: 59871cf28ed0
Revises: 
Create Date: 2025-05-05 22:48:36.320466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59871cf28ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('inventariable', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], name='fk_producto_marca'),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], name='fk_producto_modelo'),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_productos.id'], name='fk_producto_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades_organizativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'sede_id', name='uq_unidad_sede')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_organizativa_id', sa.Integer(), nullable=False),
    sa.Column('es_deposito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_organizativa_id'], ['unidades_organizativas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'unidad_organizativa_id', name='uq_area_unidad')
    )
    op.create_table('stock_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('producto_nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'codigo', name='uq_area_codigo')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_origen_id', sa.Integer(), nullable=True),
    sa.Column('stock_destino_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['stock_destino_id'], ['stock_ubicacion.id'], ),
    sa.ForeignKeyConstraint(['stock_origen_id'], ['stock_ubicacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_stock')
    op.drop_table('stock_ubicacion')
    op.drop_table('areas')
    op.drop_table('unidades_organizativas')
    op.drop_table('productos')
    op.drop_table('tipos_productos')
    op.drop_table('sedes')
    op.drop_table('modelos')
    op.drop_table('marcas')
    # ### end Alembic commands ###
