"""Agregado campo descripcion a Sede

Revision ID: 93d738242157
Revises: 59871cf28ed0
Create Date: 2025-05-07 22:09:31.198139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d738242157'
down_revision = '59871cf28ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
